name: mangas 4287 - 6430
'on':
  schedule:
  - cron: 0 12 * * 0
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install requests bs4 scikit-learn
    - name: Pull latest manga information
      run: python 01_scrape_mangas.py 4287 6430
    - name: Calculate similar mangas
      run: python 02_calc_similarities.py 4287 6430
    - name: Commit changed files
      run: 'git config --local user.email "action@github.com" && git config --local
        user.name "GitHub Action" && git commit -m "Updated Manga 4287 - 6430" -a '
    - name: Push changes to master branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
