name: Daily Related Manga Update

on:
  schedule:
    - cron: '22 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 360
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 scikit-learn

    - name: Update Master Manga List
      run: python 01_scrape_mangas.py
    - name: Find Related Mangas
      run: python 02_calc_similarities.py
      
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Updated Related Manga JSON" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload The Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "https://uploads.github.com/repos/goldbattle/MangadexRecomendations/releases/1/assets"
        asset_path: output/mangas_compressed.json
        asset_name: mangas_compressed.json
        asset_content_type: application/json
